apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quasar-myquasarapp
  labels:
    app: quasar-myquasarapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # @custom: set storage capacity
      storage: 1Gi
