apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example.net
  namespace: default
spec:
  secretName: tls-example.net
  issuerRef:
    # @custom: provide the certificate issuer here
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - example.net
  # if you wish to access the staging app from outside using https
  # - stg.example.net
